import { Link } from 'react-router-dom';
import { ArrowRight, FilePlus, ShieldCheck } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { JOB_STATUS, formatRelativeTime } from '../../utils/constants';
import PageTransition from '../../components/common/PageTransition';

export default function CustomerDashboard() {
 const { jobs, currentUser } = useApp(); const mine=jobs.filter(j=>!currentUser?.id || j.customerId===currentUser?.id || j.user_id===currentUser?.id); const active=mine.filter(j=>!['DESTROYED','EXPIRED','FAILED'].includes(j.status)); const removed=mine.filter(j=>j.status===JOB_STATUS.DESTROYED);
 return <PageTransition><main className="vault-page"><div className="vault-wrap"><header className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="vault-kicker">Customer space</p><h1 className="vault-title !text-[clamp(2.5rem,5vw,4.7rem)]">Your print<br/><em>journey.</em></h1><p className="vault-lede">Create a temporary print handoff and follow its status from one place.</p></div><Link to="/customer/upload" className="vault-button"><FilePlus size={16}/> New print job</Link></header><section className="vault-statline"><div className="vault-stat"><strong>{active.length}</strong><span>Active handoffs</span></div><div className="vault-stat"><strong>{removed.length}</strong><span>Removal recorded</span></div><div className="vault-stat"><strong>{mine.length}</strong><span>All print jobs</span></div></section><section className="vault-section"><div className="flex items-end justify-between"><div><p className="vault-kicker">Recent work</p><h2 className="mt-3 text-2xl text-[var(--paper)] font-serif">What’s happening now</h2></div><Link className="text-sm text-[var(--lime)]" to="/customer/jobs">View all</Link></div><div className="vault-list">{mine.slice(0,5).map(job=><Link className="vault-row hover:bg-white/[.03] px-3 -mx-3" key={job.id} to={`/customer/jobs/${job.id}`}><div><strong className="text-[var(--paper)]">{job.fileName}</strong><p className="mt-1 text-xs text-slate-500">{job.printId} · {formatRelativeTime(job.createdAt)}</p></div><div className="text-right"><span className="vault-status">{job.status.replaceAll('_',' ')}</span><ArrowRight size={15} className="mt-2 ml-auto text-slate-500"/></div></Link>)}{mine.length===0&&<div className="vault-panel text-slate-400">No jobs yet. Start with a temporary Print ID.</div>}</div></section><aside className="vault-panel flex gap-3"><ShieldCheck className="shrink-0 text-[var(--lime)]"/><p className="text-sm text-slate-300">Share only the Print ID with the shop. Keep the original document private.</p></aside></div></main></PageTransition>;
}